import base64
from src.api.utils.llm.get_llm_type import get_model_type
from src.api import config


def get_initial_message(llm_name, question):
    content = [
        {"type": "text", "text": "You are a Verilog code generator. Please provide the code starts with ```verilog\n and ends with ```\n."},
        {"type": "text", "text": "This is the description of the functionality of the circuit:"},
        {"type": "text", "text": question},
    ]
    return [{"role": "user", "content": content}]


def get_syntax_error_message(llm_name, verilog_code, error_message, question):
    content = [
        {"type": "text", "text": "You are a Verilog code generator. Please provide the code starts with ```\n and ends with \n```."},
        {"type": "text", "text": "Please review the error message and modify the Verilog code accordingly."},
        {"type": "text", "text": "This is the error verilog code:"},
        {"type": "text", "text": "```\\n" + verilog_code + "\\n```"},
        {"type": "text", "text": "This is the error message:"},
        {"type": "text", "text": "```\\n" + error_message + "\\n```"},
        {"type": "text", "text": "This is the description of the functionality of the circuit:"},
        {"type": "text", "text": "```\\n" + question + "\\n```"},
    ]
    return [{"role": "user", "content": content}]


def get_testbench_error_message(llm_name, verilog_code, testbench_code, testbench_response, question, if_generate_waveform=False):
    content = [
        {"type": "text", "text": "You are a Verilog code generator. Please provide the code starts with ```\n and ends with \n```."},
        {"type": "text", "text": "Please review the testbench result and modify the Verilog code accordingly."},
        {"type": "text", "text": "This is the error Verilog code:"},
        {"type": "text", "text": f"```\\n{verilog_code}\\n```"},
        {"type": "text", "text": "This is the testbench code:"},
        {"type": "text", "text": f"```\\n{testbench_code}\\n```"},
        {"type": "text", "text": "This is the testbench response:"},
        {"type": "text", "text": f"```\\n{testbench_response}\\n```"},
        {"type": "text", "text": "This is the description of the functionality of the circuit:"},
        {"type": "text", "text": f"```\\n{question}\\n```"},
    ]

    if if_generate_waveform:
        waveform_path = config.SRC_DIR / "vlog_workspace" / "waveform.png"
        with open(waveform_path, "rb") as f:
            base64_image = base64.b64encode(f.read()).decode("utf-8")
        content.extend([
            {"type": "text", "text": "This is the waveform generated by running the answer through the testbench."},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}},
        ])

    return [{"role": "user", "content": content}]
